name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  schedule:
    - cron: '30 19 * * *'
jobs:
  tests:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Generate string with ANSI color codes
        id: generate-colored-output
        run: |
          colored=$(printf '\e[0;31mCOLORED\e[0m')
          echo "::set-output name=colored::$colored"
      - name: Assert ANSI color codes present in input string
        run: |
          if [[ "${{ steps.generate-colored-output.outputs.colored }}" != $(printf '\e[0;31mCOLORED\e[0m') ]]; then
              echo "Test string should contain ANSI color codes"
              exit 1
          fi
      - name: Remove ANSI color codes
        uses: ./
        id: remove-ansi-colors
        with:
          colored: ${{ steps.generate-colored-output.outputs.colored }}
      - name: Assert ANSI color codes removed from output string
        run: |
          if [[ "${{ steps.remove-ansi-colors.outputs.uncolored }}" != "COLORED" ]]; then
              echo "Output string should not contain ANSI color codes"
              exit 1
          fi
    